// ============ PAGE: SEVKİYAT ============
function renderShipping() {
  const orders = DB.get('customer_orders'); const shipments = DB.get('shipments') || []; const readyOrders = orders.filter(o => o.status === 'ready_to_ship'); const pastShipments = shipments.sort((a,b) => new Date(b.date) - new Date(a.date));
  const readyRows = readyOrders.map(o => `<tr class="border-b border-slate-100 dark:border-slate-700/50 hover:bg-slate-50 dark:hover:bg-slate-800/50 text-sm transition"><td class="py-3 px-4 font-mono font-bold text-purple-600 dark:text-purple-400">${o.orderNo}</td><td class="py-3 px-4 font-medium">${o.customer}</td><td class="py-3 px-4">${o.product}</td><td class="py-3 px-4 text-right font-bold">${o.quantity}</td><td class="py-3 px-4 text-right"><button onclick="showShipModal(${o.id})" class="px-4 py-2 bg-indigo-600 text-white rounded-lg text-xs font-bold hover:bg-indigo-700 shadow-sm flex items-center gap-1 ml-auto"><i data-lucide="truck" class="w-4 h-4"></i> Sevk Et</button></td></tr>`).join('');
  const historyRows = pastShipments.map(sh => { const o = orders.find(x => x.id === sh.orderId) || {}; return `<tr class="border-b border-slate-100 dark:border-slate-700/50 text-sm"><td class="py-3 px-4 text-slate-500">${formatDate(sh.date)}</td><td class="py-3 px-4 font-mono text-slate-700 dark:text-slate-300">${o.orderNo || '-'}</td><td class="py-3 px-4">${o.customer || '-'}</td><td class="py-3 px-4 font-bold">${sh.carrier}</td><td class="py-3 px-4 font-mono text-xs">${sh.trackingNo || '-'}</td><td class="py-3 px-4"><span class="px-2 py-1 rounded-full text-xs font-bold bg-teal-100 text-teal-700 dark:bg-teal-900/40 dark:text-teal-400 border border-teal-200 dark:border-teal-800"><i data-lucide="check" class="w-3 h-3 inline mr-0.5"></i> Yolda</span></td></tr>`; }).join('');
  return `<div class="max-w-7xl mx-auto space-y-8"><div class="bg-white dark:bg-slate-800 rounded-xl border border-slate-200 dark:border-slate-700 overflow-hidden shadow-sm"><div class="px-5 py-4 border-b border-purple-100 dark:border-slate-700 bg-purple-50 dark:bg-slate-800/80 flex justify-between items-center"><h3 class="font-bold text-sm text-purple-800 dark:text-purple-400 flex items-center gap-2"><i data-lucide="package-check" class="w-5 h-5"></i> Üretimi Bitenler (Sevkiyat Bekleyen Siparişler)</h3></div><table class="w-full text-left"><thead><tr class="text-xs font-bold text-slate-500 bg-slate-50 dark:bg-slate-900/50 border-b border-slate-200 dark:border-slate-700 uppercase tracking-wider"><th class="py-3 px-4">Sipariş No</th><th class="py-3 px-4">Müşteri</th><th class="py-3 px-4">Ürün</th><th class="py-3 px-4 text-right">Miktar</th><th class="py-3 px-4 text-right">İşlem</th></tr></thead><tbody>${readyRows || `<tr><td colspan="5" class="text-center py-10 text-sm text-slate-500">Şu anda sevkiyat bekleyen sipariş bulunmuyor.</td></tr>`}</tbody></table></div><div class="bg-white dark:bg-slate-800 rounded-xl border border-slate-200 dark:border-slate-700 overflow-hidden shadow-sm"><div class="px-5 py-4 border-b border-slate-200 dark:border-slate-700 bg-slate-50 dark:bg-slate-800/80 flex justify-between items-center"><h3 class="font-bold text-sm text-slate-700 dark:text-slate-300 flex items-center gap-2"><i data-lucide="history" class="w-5 h-5"></i> Sevkiyat Geçmişi</h3></div><table class="w-full text-left"><thead><tr class="text-xs font-bold text-slate-500 bg-slate-50 dark:bg-slate-900/50 border-b border-slate-200 dark:border-slate-700 uppercase tracking-wider"><th class="py-3 px-4">Sevk Tarihi</th><th class="py-3 px-4">Sipariş No</th><th class="py-3 px-4">Müşteri</th><th class="py-3 px-4">Kargo/Nakliye Firması</th><th class="py-3 px-4">İrsaliye/Takip No</th><th class="py-3 px-4">Durum</th></tr></thead><tbody>${historyRows || `<tr><td colspan="6" class="text-center py-10 text-sm text-slate-500">Geçmiş sevkiyat kaydı bulunmuyor.</td></tr>`}</tbody></table></div></div>`;
}

function showShipModal(orderId) {
  const o = DB.get('customer_orders').find(x => x.id === orderId); if(!o) return;
  showModal('Sevkiyat Oluştur', `<div class="space-y-4"><div class="bg-purple-50 dark:bg-purple-900/20 p-4 rounded-xl border border-purple-100 dark:border-purple-800/50 text-sm shadow-inner"><div class="flex justify-between mb-2"><span class="text-slate-500">Sipariş No:</span> <span class="font-bold text-purple-700 font-mono">${o.orderNo}</span></div><div class="flex justify-between mb-2"><span class="text-slate-500">Müşteri:</span> <span class="font-bold">${o.customer}</span></div><div class="flex justify-between"><span class="text-slate-500">Sevk Edilecek Ürün:</span> <span class="font-bold">${o.product} (${o.quantity} Adet)</span></div></div><div><label class="text-xs font-bold text-slate-500 uppercase">Kargo / Nakliye Firması</label><input id="f-shipCarrier" class="w-full mt-1 px-3 py-3 text-sm border border-slate-300 dark:border-slate-600 rounded-lg dark:bg-slate-700 focus:ring-2 focus:ring-indigo-500 outline-none" placeholder="Örn: Yurtiçi Kargo, X Lojistik"></div><div><label class="text-xs font-bold text-slate-500 uppercase">İrsaliye / Takip No</label><input id="f-shipTrack" class="w-full mt-1 px-3 py-3 text-sm border border-slate-300 dark:border-slate-600 rounded-lg dark:bg-slate-700 focus:ring-2 focus:ring-indigo-500 outline-none" placeholder="Örn: TR-987654321"></div><div><label class="text-xs font-bold text-slate-500 uppercase">Sevk Tarihi</label><input type="date" id="f-shipDate" class="w-full mt-1 px-3 py-3 text-sm border border-slate-300 dark:border-slate-600 rounded-lg dark:bg-slate-700 focus:ring-2 focus:ring-indigo-500 outline-none" value="${new Date().toISOString().slice(0,10)}"></div></div>`, () => {
     const carrier = document.getElementById('f-shipCarrier').value.trim(); const track = document.getElementById('f-shipTrack').value.trim(); const date = document.getElementById('f-shipDate').value;
     if(!carrier) return toast('Kargo firması zorunludur', 'error');
     const shipments = DB.get('shipments') || []; shipments.push({ id: DB.nextId('shipments'), orderId: o.id, carrier, trackingNo: track, date, status: 'shipped' }); DB.set('shipments', shipments);
     const orders = DB.get('customer_orders'); const orderIndex = orders.findIndex(x => x.id === o.id);
     if(orderIndex !== -1) { orders[orderIndex].status = 'shipped'; DB.set('customer_orders', orders); }
     closeModal(); toast('Sevkiyat oluşturuldu!', 'success'); render();
  });
  const btn = document.getElementById('modal-save-btn'); btn.textContent = "Yola Çıkar"; btn.className = "px-6 py-2.5 text-sm rounded-lg bg-indigo-600 text-white hover:bg-indigo-700 font-bold shadow-md flex items-center gap-2"; btn.innerHTML = `<i data-lucide="truck" class="w-4 h-4"></i> Yola Çıkar`; lucide.createIcons();
}

